os: linux
dist: xenial
virt: lxd
arch: arm64-graviton2
language: java

jdk:
  - openjdk11

services:
  - docker

before_install:
  - sudo apt update
  - sudo apt install maven
  - mvn --version

script:
  - mvn clean verify -B
